### ISSUE TITLE
Для чего изменять assets.rb? 

### ISSUE THREAD

**Issue by mrPsycho** [noshutdown-ru/vault#10]
Здравствуйте,
у вас есть это: 
`Add Rails.application.config.assets.precompile += %w( zeroclipboard.js ) to config/initializers/assets.rb and restart your server.`

 и судя по всему, при каждом обновлении надо это делать заного.
планируете ли вы фикс, который позволит безболезненно обновлять редмайн?
ну и... насколько критично это изменение?

**Comment by noshutdown-ru-user** [comment]
Добрый день.
Это нужно делать не при каждом обновлении а только при установке.
Это необходимо что бы gem zeroclipboard - работал.
zeroclipboard нужен для того что бы работало копирование в буфер.

**Comment by mrPsycho** [comment]
а, понял. значит не критично. 
Спасибо!
