### ISSUE TITLE
Translation problem

### ISSUE THREAD

**Issue by mrPsycho** [noshutdown-ru/vault#12]
In project tab:
![in project](http://storage9.static.itmages.com/i/17/1018/h_1508331472_7924313_74d9257cc8.png)

Settings:
![settings](http://storage5.static.itmages.com/i/17/1018/h_1508331531_2422408_154e3dd414.png)

redmine is 3.4.2.stable
vault is 0.3.2
default language English
personal language is also English

**Comment by noshutdown-ru-user** [comment]
Fixed in 0.3.3
