### ISSUE TITLE
Error on searching by name / URL

### ISSUE THREAD

**Issue by Yopii** [noshutdown-ru/vault#13]
Hello,

Your plugin responds perfectly to my need.

However, I get an error when searching for a key by name or URL.

> Started GET "/projects/project/keys?utf8=%E2%9C%93&query=PostgreSQL&search_fild=name&commit=Mettre+%C3%A0+jour" for xxx.xxx.xxx.xxx at 2017-10-21 18:18:52 +0200
Processing by KeysController#index as HTML
  Parameters: {"utf8"=>"✓", "query"=>"PostgreSQL", "search_fild"=>"name", "commit"=>"Mettre à jour", "project_id"=>"project"}
  Current user: xxxxx (id=5)
Completed 500 Internal Server Error in 15ms (ActiveRecord: 7.9ms)

> ActiveRecord::StatementInvalid (PG::UndefinedFunction: ERREUR:  l'opérateur n'existe pas : ` character varying
LINE 1: ...) FROM "keys" WHERE "keys"."project_id" = $1 AND (`name` LIK...
                                                             ^
> HINT:  Aucun opérateur ne correspond au nom donné et aux types d'arguments.
Vous devez ajouter des conversions explicites de type.
: SELECT COUNT(*) FROM "keys" WHERE "keys"."project_id" = $1 AND (`name` LIKE '%PostgreSQL%')):
  plugins/vault/app/controllers/keys_controller.rb:55:in `index'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'`

I was able to find a temporary solution to test it by deleting the characters " **`** " in the file 'app / controllers / keys_controller.rb'.

You will find below the configuration of my Redmine.

> Environment:
  Redmine version                3.3.4.stable.16775
  Ruby version                   2.3.4-p301 (2017-03-30) [x86_64-linux]
  Rails version                  4.2.7.1
  Environment                    production
  Database adapter               PostgreSQL
SCM:
  Subversion                     1.9.3
  Git                            2.7.4
  Filesystem                     
Redmine plugins:
  clipboard_image_paste          1.12
  redmine_agile                  1.4.5
  redmine_banner                 0.1.2
  redmine_checklists             3.1.10
  redmine_drawio                 0.8.0
  redmine_editor_preview_tab     0.1.5
  redmine_lightbox2              0.3.5
  vault                          0.3.3

Thx

**Comment by noshutdown-ru-user** [comment]
we working on it, soon it should be fixed, couple of days

**Comment by Yopii** [comment]
Perfect ! Take your time ;)
Thx

**Comment by noshutdown-ru-user** [comment]
Fixed in https://github.com/noshutdown-ru/vault/tree/development
