### ISSUE TITLE
iconv fail

### ISSUE THREAD

**Issue by neocosmic2** [noshutdown-ru/vault#15]
I have been trying to install this plugin so long, but always stopped at gem iconv.
Im using bitnami with ruby 2.3.0. hope there is an advice for me.

have_func: checking for rb_enc_get() in ruby/encoding.h... -------------------- yes

"gcc -o conftest.exe -IC:/Bitnami/redmine-3.4.2-4/ruby/include/ruby-2.3.0/i386-mingw32 -IC:/Bitnami/redmine-3.4.2-4/ruby/include/ruby-2.3.0/ruby/backward -IC:/Bitnami/redmine-3.4.2-4/ruby/include/ruby-2.3.0 -I. -IC:\Program/include -DFD_SETSIZE=2048 -D_WIN32_WINNT=0x0501 -D__MINGW_USE_VC2005_COMPAT -D_FILE_OFFSET_BITS=64   -O3 -fno-omit-frame-pointer -fno-fast-math -g -Wall -Wextra -Wno-unused-parameter -Wno-parentheses -Wno-long-long -Wno-missing-field-initializers -Wunused-variable -Wpointer-arith -Wwrite-strings -Wdeclaration-after-statement -Wimplicit-function-declaration -Wdeprecated-declarations -Wno-packed-bitfield-compat conftest.c  -L. -LC:/Bitnami/redmine-3.4.2-4/ruby/lib -LC:\Program/lib -L.      -lmsvcrt-ruby230  -lshell32 -lws2_32 -liphlpapi -limagehlp -lshlwapi  "
In file included from C:/Bitnami/redmine-3.4.2-4/ruby/include/ruby-2.3.0/ruby/defines.h:168:0,
                 from C:/Bitnami/redmine-3.4.2-4/ruby/include/ruby-2.3.0/ruby/ruby.h:36,
                 from C:/Bitnami/redmine-3.4.2-4/ruby/include/ruby-2.3.0/ruby.h:33,
                 from conftest.c:1:
C:/Bitnami/redmine-3.4.2-4/ruby/include/ruby-2.3.0/ruby/win32.h:295:44: warning: 'struct timespec' declared inside parameter list
C:/Bitnami/redmine-3.4.2-4/ruby/include/ruby-2.3.0/ruby/win32.h:295:44: warning: its scope is only this definition or declaration, which is probably not what you want
C:/Bitnami/redmine-3.4.2-4/ruby/include/ruby-2.3.0/ruby/win32.h:296:43: warning: 'struct timespec' declared inside parameter list
In file included from C:/Bitnami/redmine-3.4.2-4/ruby/include/ruby-2.3.0/ruby/ruby.h:1992:0,
                 from C:/Bitnami/redmine-3.4.2-4/ruby/include/ruby-2.3.0/ruby.h:33,
                 from conftest.c:1:
C:/Bitnami/redmine-3.4.2-4/ruby/include/ruby-2.3.0/ruby/intern.h:923:29: warning: 'struct timespec' declared inside parameter list
C:/Bitnami/redmine-3.4.2-4/ruby/include/ruby-2.3.0/ruby/intern.h:926:41: warning: 'struct timespec' declared inside parameter list
checked program was:
/* begin */
1: #include "ruby.h"
2: 
3: #include <winsock2.h>
4: #include <windows.h>
5: int main(int argc, char **argv)
6: {
7:   return 0;
8: }
/* end */

"gcc -o conftest.exe -IC:/Bitnami/redmine-3.4.2-4/ruby/include/ruby-2.3.0/i386-mingw32 -IC:/Bitnami/redmine-3.4.2-4/ruby/include/ruby-2.3.0/ruby/backward -IC:/Bitnami/redmine-3.4.2-4/ruby/include/ruby-2.3.0 -I. -IC:\Program/include -DFD_SETSIZE=2048 -D_WIN32_WINNT=0x0501 -D__MINGW_USE_VC2005_COMPAT -D_FILE_OFFSET_BITS=64   -O3 -fno-omit-frame-pointer -fno-fast-math -g -Wall -Wextra -Wno-unused-parameter -Wno-parentheses -Wno-long-long -Wno-missing-field-initializers -Wunused-variable -Wpointer-arith -Wwrite-strings -Wdeclaration-after-statement -Wimplicit-function-declaration -Wdeprecated-declarations -Wno-packed-bitfield-compat conftest.c  -L. -LC:/Bitnami/redmine-3.4.2-4/ruby/lib -LC:\Program/lib -L.      -lmsvcrt-ruby230  -lshell32 -lws2_32 -liphlpapi -limagehlp -lshlwapi  "
In file included from C:/Bitnami/redmine-3.4.2-4/ruby/include/ruby-2.3.0/ruby/defines.h:168:0,
                 from C:/Bitnami/redmine-3.4.2-4/ruby/include/ruby-2.3.0/ruby/ruby.h:36,
                 from C:/Bitnami/redmine-3.4.2-4/ruby/include/ruby-2.3.0/ruby.h:33,
                 from conftest.c:1:
C:/Bitnami/redmine-3.4.2-4/ruby/include/ruby-2.3.0/ruby/win32.h:295:44: warning: 'struct timespec' declared inside parameter list
C:/Bitnami/redmine-3.4.2-4/ruby/include/ruby-2.3.0/ruby/win32.h:295:44: warning: its scope is only this definition or declaration, which is probably not what you want
C:/Bitnami/redmine-3.4.2-4/ruby/include/ruby-2.3.0/ruby/win32.h:296:43: warning: 'struct timespec' declared inside parameter list
In file included from C:/Bitnami/redmine-3.4.2-4/ruby/include/ruby-2.3.0/ruby/ruby.h:1992:0,
                 from C:/Bitnami/redmine-3.4.2-4/ruby/include/ruby-2.3.0/ruby.h:33,
                 from conftest.c:1:
C:/Bitnami/redmine-3.4.2-4/ruby/include/ruby-2.3.0/ruby/intern.h:923:29: warning: 'struct timespec' declared inside parameter list
C:/Bitnami/redmine-3.4.2-4/ruby/include/ruby-2.3.0/ruby/intern.h:926:41: warning: 'struct timespec' declared inside parameter list
checked program was:
/* begin */
 1: #include "ruby.h"
 2: 
 3: #include <winsock2.h>
 4: #include <windows.h>
 5: #include <ruby/encoding.h>
 6: 
 7: /*top*/
 8: extern int t(void);
 9: int main(int argc, char **argv)
10: {
11:   if (argc > 1000000) {
12:     printf("%p", &t);
13:   }
14: 
15:   return 0;
16: }
17: int t(void) { void ((*volatile p)()); p = (void ((*)()))rb_enc_get; return !p; }
/* end */

--------------------

have_func: checking for rb_sys_fail_str() in ruby.h... -------------------- yes

"gcc -o conftest.exe -IC:/Bitnami/redmine-3.4.2-4/ruby/include/ruby-2.3.0/i386-mingw32 -IC:/Bitnami/redmine-3.4.2-4/ruby/include/ruby-2.3.0/ruby/backward -IC:/Bitnami/redmine-3.4.2-4/ruby/include/ruby-2.3.0 -I. -IC:\Program/include -DFD_SETSIZE=2048 -D_WIN32_WINNT=0x0501 -D__MINGW_USE_VC2005_COMPAT -D_FILE_OFFSET_BITS=64   -O3 -fno-omit-frame-pointer -fno-fast-math -g -Wall -Wextra -Wno-unused-parameter -Wno-parentheses -Wno-long-long -Wno-missing-field-initializers -Wunused-variable -Wpointer-arith -Wwrite-strings -Wdeclaration-after-statement -Wimplicit-function-declaration -Wdeprecated-declarations -Wno-packed-bitfield-compat conftest.c  -L. -LC:/Bitnami/redmine-3.4.2-4/ruby/lib -LC:\Program/lib -L.      -lmsvcrt-ruby230  -lshell32 -lws2_32 -liphlpapi -limagehlp -lshlwapi  "
In file included from C:/Bitnami/redmine-3.4.2-4/ruby/include/ruby-2.3.0/ruby/defines.h:168:0,
                 from C:/Bitnami/redmine-3.4.2-4/ruby/include/ruby-2.3.0/ruby/ruby.h:36,
                 from C:/Bitnami/redmine-3.4.2-4/ruby/include/ruby-2.3.0/ruby.h:33,
                 from conftest.c:1:
C:/Bitnami/redmine-3.4.2-4/ruby/include/ruby-2.3.0/ruby/win32.h:295:44: warning: 'struct timespec' declared inside parameter list
C:/Bitnami/redmine-3.4.2-4/ruby/include/ruby-2.3.0/ruby/win32.h:295:44: warning: its scope is only this definition or declaration, which is probably not what you want
C:/Bitnami/redmine-3.4.2-4/ruby/include/ruby-2.3.0/ruby/win32.h:296:43: warning: 'struct timespec' declared inside parameter list
In file included from C:/Bitnami/redmine-3.4.2-4/ruby/include/ruby-2.3.0/ruby/ruby.h:1992:0,
                 from C:/Bitnami/redmine-3.4.2-4/ruby/include/ruby-2.3.0/ruby.h:33,
                 from conftest.c:1:
C:/Bitnami/redmine-3.4.2-4/ruby/include/ruby-2.3.0/ruby/intern.h:923:29: warning: 'struct timespec' declared inside parameter list
C:/Bitnami/redmine-3.4.2-4/ruby/include/ruby-2.3.0/ruby/intern.h:926:41: warning: 'struct timespec' declared inside parameter list
checked program was:
/* begin */
 1: #include "ruby.h"
 2: 
 3: #include <winsock2.h>
 4: #include <windows.h>
 5: #include <ruby.h>
 6: 
 7: /*top*/
 8: extern int t(void);
 9: int main(int argc, char **argv)
10: {
11:   if (argc > 1000000) {
12:     printf("%p", &t);
13:   }
14: 
15:   return 0;
16: }
17: int t(void) { void ((*volatile p)()); p = (void ((*)()))rb_sys_fail_str; return !p; }
/* end */

--------------------

have_func: checking for iconv() in iconv.h... -------------------- no

"gcc -o conftest.exe -IC:/Bitnami/redmine-3.4.2-4/ruby/include/ruby-2.3.0/i386-mingw32 -IC:/Bitnami/redmine-3.4.2-4/ruby/include/ruby-2.3.0/ruby/backward -IC:/Bitnami/redmine-3.4.2-4/ruby/include/ruby-2.3.0 -I. -IC:\Program/include -DFD_SETSIZE=2048 -D_WIN32_WINNT=0x0501 -D__MINGW_USE_VC2005_COMPAT -D_FILE_OFFSET_BITS=64   -O3 -fno-omit-frame-pointer -fno-fast-math -g -Wall -Wextra -Wno-unused-parameter -Wno-parentheses -Wno-long-long -Wno-missing-field-initializers -Wunused-variable -Wpointer-arith -Wwrite-strings -Wdeclaration-after-statement -Wimplicit-function-declaration -Wdeprecated-declarations -Wno-packed-bitfield-compat conftest.c  -L. -LC:/Bitnami/redmine-3.4.2-4/ruby/lib -LC:\Program/lib -L.      -lmsvcrt-ruby230  -lshell32 -lws2_32 -liphlpapi -limagehlp -lshlwapi  "
In file included from C:/Bitnami/redmine-3.4.2-4/ruby/include/ruby-2.3.0/ruby/defines.h:168:0,
                 from C:/Bitnami/redmine-3.4.2-4/ruby/include/ruby-2.3.0/ruby/ruby.h:36,
                 from C:/Bitnami/redmine-3.4.2-4/ruby/include/ruby-2.3.0/ruby.h:33,
                 from conftest.c:1:
C:/Bitnami/redmine-3.4.2-4/ruby/include/ruby-2.3.0/ruby/win32.h:295:44: warning: 'struct timespec' declared inside parameter list
C:/Bitnami/redmine-3.4.2-4/ruby/include/ruby-2.3.0/ruby/win32.h:295:44: warning: its scope is only this definition or declaration, which is probably not what you want
C:/Bitnami/redmine-3.4.2-4/ruby/include/ruby-2.3.0/ruby/win32.h:296:43: warning: 'struct timespec' declared inside parameter list
In file included from C:/Bitnami/redmine-3.4.2-4/ruby/include/ruby-2.3.0/ruby/ruby.h:1992:0,
                 from C:/Bitnami/redmine-3.4.2-4/ruby/include/ruby-2.3.0/ruby.h:33,
                 from conftest.c:1:
C:/Bitnami/redmine-3.4.2-4/ruby/include/ruby-2.3.0/ruby/intern.h:923:29: warning: 'struct timespec' declared inside parameter list
C:/Bitnami/redmine-3.4.2-4/ruby/include/ruby-2.3.0/ruby/intern.h:926:41: warning: 'struct timespec' declared inside parameter list
conftest.c:5:19: fatal error: iconv.h: No such file or directory
compilation terminated.
checked program was:
/* begin */
 1: #include "ruby.h"
 2: 
 3: #include <winsock2.h>
 4: #include <windows.h>
 5: #include <iconv.h>
 6: 
 7: /*top*/
 8: extern int t(void);
 9: int main(int argc, char **argv)
10: {
11:   if (argc > 1000000) {
12:     printf("%p", &t);
13:   }
14: 
15:   return 0;
16: }
17: int t(void) { void ((*volatile p)()); p = (void ((*)()))iconv; return !p; }
/* end */

"gcc -o conftest.exe -IC:/Bitnami/redmine-3.4.2-4/ruby/include/ruby-2.3.0/i386-mingw32 -IC:/Bitnami/redmine-3.4.2-4/ruby/include/ruby-2.3.0/ruby/backward -IC:/Bitnami/redmine-3.4.2-4/ruby/include/ruby-2.3.0 -I. -IC:\Program/include -DFD_SETSIZE=2048 -D_WIN32_WINNT=0x0501 -D__MINGW_USE_VC2005_COMPAT -D_FILE_OFFSET_BITS=64   -O3 -fno-omit-frame-pointer -fno-fast-math -g -Wall -Wextra -Wno-unused-parameter -Wno-parentheses -Wno-long-long -Wno-missing-field-initializers -Wunused-variable -Wpointer-arith -Wwrite-strings -Wdeclaration-after-statement -Wimplicit-function-declaration -Wdeprecated-declarations -Wno-packed-bitfield-compat conftest.c  -L. -LC:/Bitnami/redmine-3.4.2-4/ruby/lib -LC:\Program/lib -L.      -lmsvcrt-ruby230  -lshell32 -lws2_32 -liphlpapi -limagehlp -lshlwapi  "
In file included from C:/Bitnami/redmine-3.4.2-4/ruby/include/ruby-2.3.0/ruby/defines.h:168:0,
                 from C:/Bitnami/redmine-3.4.2-4/ruby/include/ruby-2.3.0/ruby/ruby.h:36,
                 from C:/Bitnami/redmine-3.4.2-4/ruby/include/ruby-2.3.0/ruby.h:33,
                 from conftest.c:1:
C:/Bitnami/redmine-3.4.2-4/ruby/include/ruby-2.3.0/ruby/win32.h:295:44: warning: 'struct timespec' declared inside parameter list
C:/Bitnami/redmine-3.4.2-4/ruby/include/ruby-2.3.0/ruby/win32.h:295:44: warning: its scope is only this definition or declaration, which is probably not what you want
C:/Bitnami/redmine-3.4.2-4/ruby/include/ruby-2.3.0/ruby/win32.h:296:43: warning: 'struct timespec' declared inside parameter list
In file included from C:/Bitnami/redmine-3.4.2-4/ruby/include/ruby-2.3.0/ruby/ruby.h:1992:0,
                 from C:/Bitnami/redmine-3.4.2-4/ruby/include/ruby-2.3.0/ruby.h:33,
                 from conftest.c:1:
C:/Bitnami/redmine-3.4.2-4/ruby/include/ruby-2.3.0/ruby/intern.h:923:29: warning: 'struct timespec' declared inside parameter list
C:/Bitnami/redmine-3.4.2-4/ruby/include/ruby-2.3.0/ruby/intern.h:926:41: warning: 'struct timespec' declared inside parameter list
conftest.c:5:19: fatal error: iconv.h: No such file or directory
compilation terminated.
checked program was:
/* begin */
 1: #include "ruby.h"
 2: 
 3: #include <winsock2.h>
 4: #include <windows.h>
 5: #include <iconv.h>
 6: 
 7: /*top*/
 8: extern int t(void);
 9: int main(int argc, char **argv)
10: {
11:   if (argc > 1000000) {
12:     printf("%p", &t);
13:   }
14: 
15:   return 0;
16: }
17: extern void iconv();
18: int t(void) { iconv(); return 0; }
/* end */

--------------------

have_library: checking for iconv() in -liconv... -------------------- no

"gcc -o conftest.exe -IC:/Bitnami/redmine-3.4.2-4/ruby/include/ruby-2.3.0/i386-mingw32 -IC:/Bitnami/redmine-3.4.2-4/ruby/include/ruby-2.3.0/ruby/backward -IC:/Bitnami/redmine-3.4.2-4/ruby/include/ruby-2.3.0 -I. -IC:\Program/include -DFD_SETSIZE=2048 -D_WIN32_WINNT=0x0501 -D__MINGW_USE_VC2005_COMPAT -D_FILE_OFFSET_BITS=64   -O3 -fno-omit-frame-pointer -fno-fast-math -g -Wall -Wextra -Wno-unused-parameter -Wno-parentheses -Wno-long-long -Wno-missing-field-initializers -Wunused-variable -Wpointer-arith -Wwrite-strings -Wdeclaration-after-statement -Wimplicit-function-declaration -Wdeprecated-declarations -Wno-packed-bitfield-compat conftest.c  -L. -LC:/Bitnami/redmine-3.4.2-4/ruby/lib -LC:\Program/lib -L.      -lmsvcrt-ruby230 -liconv  -lshell32 -lws2_32 -liphlpapi -limagehlp -lshlwapi  "
In file included from C:/Bitnami/redmine-3.4.2-4/ruby/include/ruby-2.3.0/ruby/defines.h:168:0,
                 from C:/Bitnami/redmine-3.4.2-4/ruby/include/ruby-2.3.0/ruby/ruby.h:36,
                 from C:/Bitnami/redmine-3.4.2-4/ruby/include/ruby-2.3.0/ruby.h:33,
                 from conftest.c:1:
C:/Bitnami/redmine-3.4.2-4/ruby/include/ruby-2.3.0/ruby/win32.h:295:44: warning: 'struct timespec' declared inside parameter list
C:/Bitnami/redmine-3.4.2-4/ruby/include/ruby-2.3.0/ruby/win32.h:295:44: warning: its scope is only this definition or declaration, which is probably not what you want
C:/Bitnami/redmine-3.4.2-4/ruby/include/ruby-2.3.0/ruby/win32.h:296:43: warning: 'struct timespec' declared inside parameter list
In file included from C:/Bitnami/redmine-3.4.2-4/ruby/include/ruby-2.3.0/ruby/ruby.h:1992:0,
                 from C:/Bitnami/redmine-3.4.2-4/ruby/include/ruby-2.3.0/ruby.h:33,
                 from conftest.c:1:
C:/Bitnami/redmine-3.4.2-4/ruby/include/ruby-2.3.0/ruby/intern.h:923:29: warning: 'struct timespec' declared inside parameter list
C:/Bitnami/redmine-3.4.2-4/ruby/include/ruby-2.3.0/ruby/intern.h:926:41: warning: 'struct timespec' declared inside parameter list
conftest.c:5:19: fatal error: iconv.h: No such file or directory
compilation terminated.
checked program was:
/* begin */
 1: #include "ruby.h"
 2: 
 3: #include <winsock2.h>
 4: #include <windows.h>
 5: #include <iconv.h>
 6: 
 7: /*top*/
 8: extern int t(void);
 9: int main(int argc, char **argv)
10: {
11:   if (argc > 1000000) {
12:     printf("%p", &t);
13:   }
14: 
15:   return 0;
16: }
17: int t(void) { void ((*volatile p)()); p = (void ((*)()))iconv; return !p; }
/* end */

"gcc -o conftest.exe -IC:/Bitnami/redmine-3.4.2-4/ruby/include/ruby-2.3.0/i386-mingw32 -IC:/Bitnami/redmine-3.4.2-4/ruby/include/ruby-2.3.0/ruby/backward -IC:/Bitnami/redmine-3.4.2-4/ruby/include/ruby-2.3.0 -I. -IC:\Program/include -DFD_SETSIZE=2048 -D_WIN32_WINNT=0x0501 -D__MINGW_USE_VC2005_COMPAT -D_FILE_OFFSET_BITS=64   -O3 -fno-omit-frame-pointer -fno-fast-math -g -Wall -Wextra -Wno-unused-parameter -Wno-parentheses -Wno-long-long -Wno-missing-field-initializers -Wunused-variable -Wpointer-arith -Wwrite-strings -Wdeclaration-after-statement -Wimplicit-function-declaration -Wdeprecated-declarations -Wno-packed-bitfield-compat conftest.c  -L. -LC:/Bitnami/redmine-3.4.2-4/ruby/lib -LC:\Program/lib -L.      -lmsvcrt-ruby230 -liconv  -lshell32 -lws2_32 -liphlpapi -limagehlp -lshlwapi  "
In file included from C:/Bitnami/redmine-3.4.2-4/ruby/include/ruby-2.3.0/ruby/defines.h:168:0,
                 from C:/Bitnami/redmine-3.4.2-4/ruby/include/ruby-2.3.0/ruby/ruby.h:36,
                 from C:/Bitnami/redmine-3.4.2-4/ruby/include/ruby-2.3.0/ruby.h:33,
                 from conftest.c:1:
C:/Bitnami/redmine-3.4.2-4/ruby/include/ruby-2.3.0/ruby/win32.h:295:44: warning: 'struct timespec' declared inside parameter list
C:/Bitnami/redmine-3.4.2-4/ruby/include/ruby-2.3.0/ruby/win32.h:295:44: warning: its scope is only this definition or declaration, which is probably not what you want
C:/Bitnami/redmine-3.4.2-4/ruby/include/ruby-2.3.0/ruby/win32.h:296:43: warning: 'struct timespec' declared inside parameter list
In file included from C:/Bitnami/redmine-3.4.2-4/ruby/include/ruby-2.3.0/ruby/ruby.h:1992:0,
                 from C:/Bitnami/redmine-3.4.2-4/ruby/include/ruby-2.3.0/ruby.h:33,
                 from conftest.c:1:
C:/Bitnami/redmine-3.4.2-4/ruby/include/ruby-2.3.0/ruby/intern.h:923:29: warning: 'struct timespec' declared inside parameter list
C:/Bitnami/redmine-3.4.2-4/ruby/include/ruby-2.3.0/ruby/intern.h:926:41: warning: 'struct timespec' declared inside parameter list
conftest.c:5:19: fatal error: iconv.h: No such file or directory
compilation terminated.
checked program was:
/* begin */
 1: #include "ruby.h"
 2: 
 3: #include <winsock2.h>
 4: #include <windows.h>
 5: #include <iconv.h>
 6: 
 7: /*top*/
 8: extern int t(void);
 9: int main(int argc, char **argv)
10: {
11:   if (argc > 1000000) {
12:     printf("%p", &t);
13:   }
14: 
15:   return 0;
16: }
17: extern void iconv();
18: int t(void) { iconv(); return 0; }
/* end */

--------------------

**Comment by noshutdown-ru-user** [comment]
can you tryed install iconv manually ?

**Comment by neocosmic2** [comment]
tried, but still fail

**Comment by neocosmic2** [comment]
Thanks for your link, it helps . But get another problem now.

ActionView::Template::Error (Asset was not declared to be precompiled in production.
Add `Rails.application.config.assets.precompile += %w( zeroclipboard.js )` to `config/initializers/assets.rb` and restart your server):
    1: <% content_for :header_tags do %>
    2:   <%= javascript_include_tag "zeroclipboard" %>
    3:   <%#= stylesheet_link_tag "https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css" %>
    4:   <%= stylesheet_link_tag "font-awesome.css", :plugin => "vault" %>
    5:   <%= stylesheet_link_tag "font-awesome.min.css", :plugin => "vault" %>
  config/initializers/10-patches.rb:221:in `rails_asset_id'
  config/initializers/10-patches.rb:200:in `asset_path_with_asset_id'
  app/helpers/application_helper.rb:1397:in `javascript_include_tag'
  plugins/vault/app/views/keys/index.html.erb:2:in `block in _plugins_vault_app_views_keys_index_html_erb___232138023_78931188'
  plugins/vault/app/views/keys/index.html.erb:1:in `_plugins_vault_app_views_keys_index_html_erb___232138023_78931188'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'

**Comment by noshutdown-ru-user** [comment]
`When set to Redmine 3.* add
Rails.application.config.assets.precompile += %w( zeroclipboard.js )
to config/initializers/assets.rb and restart your server.`

https://noshutdown.ru/en/redmine-plugins-vault/#install
