### ISSUE TITLE
500 Internal Server Error

### ISSUE THREAD

**Issue by norlon** [noshutdown-ru/vault#16]
Processing by KeysController#index as HTML
  Parameters: {"utf8"=>"✓", "query"=>"ttt", "search_fild"=>"name", "commit"=>"Update", "project_id"=>"xgcworld"}
  Current user: admin (id=1)
Completed 500 Internal Server Error in 81ms (ActiveRecord: 62.9ms)

ActiveRecord::StatementInvalid (PG::UndefinedFunction: ERROR:  operator does not exist: ` character varying
LINE 1: ...) FROM "keys" WHERE "keys"."project_id" = $1 AND (`name` LIK...
                                                             ^
HINT:  No operator matches the given name and argument type(s). You might need to add explicit type casts.
: SELECT COUNT(*) FROM "keys" WHERE "keys"."project_id" = $1 AND (`name` LIKE '%ttt%')):
  plugins/vault/app/controllers/keys_controller.rb:55:in `index'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'

**Comment by norlon** [comment]
and patch :)

[keys_controller.rb.patch.zip](https://github.com/noshutdown-ru/vault/files/1503969/keys_controller.rb.patch.zip)

**Comment by noshutdown-ru-user** [comment]
This error looks like this #13, it already fixed in development branch

**Comment by noshutdown-ru-user** [comment]
But we very happy what you report about it, thx )
