### ISSUE TITLE
right click no url

### ISSUE THREAD

**Issue by honyee90** [noshutdown-ru/vault#17]
![image](https://user-images.githubusercontent.com/35233862/34686540-dc2355e0-f4e6-11e7-94aa-3af58f250671.png)
how to solve this problem？

**Comment by noshutdown-ru-user** [comment]
Hi, can you show redmine info ?
what redmine version you use also plugin version

**Comment by honyee90** [comment]
My environment is like this
Environment:
  Redmine version                3.4.3.stable
  Ruby version                   2.3.5-p376 (2017-09-14) [x86_64-linux]
  Rails version                  4.2.8
  Environment                    production
  Database adapter               Mysql2
SCM:
  Subversion                     1.9.7
  Git                            2.14.1
  Filesystem                     
Redmine plugins:
  clipboard_image_paste          1.12
  redmine_agile                  1.4.5
  redmine_checklists             3.1.10
  redmine_contacts               4.1.1
  redmine_issue_templates        0.1.8
  redmine_work_wechat            0.1.9
  vault                          0.3.3

**Comment by noshutdown-ru-user** [comment]
we will check it during couple of days

**Comment by noshutdown-ru-user** [comment]
can you try this branch https://github.com/noshutdown-ru/vault/tree/bug-%2317
should work

**Comment by noshutdown-ru-user** [comment]
fixed in release 0.3.4 https://github.com/noshutdown-ru/vault/releases/tag/release_0.3.4
