### ISSUE TITLE
Question - Access Control List

### ISSUE THREAD

**Issue by drewlsvern** [noshutdown-ru/vault#18]
I'm curious how the access control list rights work along with roles and permissions.

For instance, I may want all users of a specific group to be allowed to view some keys but not all. 
Currently I have a Developers group assigned to a project, and they have no permissions for keys, so they can't see the keys view at all. If I set the group's permission to be able to view keys, they see all keys in the project and the access control list doesn't seem to do anything.

Any help would be appreciated.

Current Server Config
Redmine 3.4.4
Ruby 2.4.1
Rails 4.2.8
MS SQL Server 2017
Ubuntu 16.04 LTS

**Comment by noshutdown-ru-user** [comment]
You you want manage access by white list you need to do this:

**Comment by drewlsvern** [comment]
@noshutdown-ru-user Thanks for this, much appreciated.
