### ISSUE TITLE
I don't  know how to get the Encryption keys . how?

### ISSUE THREAD

**Issue by gisok** [noshutdown-ru/vault#20]

**Comment by noshutdown-ru-user** [comment]
This is just a string, in new version we will add button for generate Encryption key.
For example you can use `apg -m 32`.

```
$ apg -m 32
ipocgajAssEivJaqueknekemrogJeOwn
CarjUcMoHiWygcapWegpybnushagsoft
lulefgiskyitevwagJeipyedupVaudJo
girentobUckDapDyWiUpveorfujOjUg6
ObrAccutfoquoiftIrloadIsunwynCaf
uvrahoighlouvIbDekEryiptAitokjuc
```

**Comment by gisok** [comment]
thanks

**Comment by gisok** [comment]
config/configuration.yml   is  in  redmine ? or plinugs/vault?
config/initializers/assets.rb is in redmine ? or  plinugs/vault?  or rails?

my system hase no assets.rb .





Redmine. Error 500
Global error
Asset was not declared to be precompiled in production. Add `Rails.application.config.assets.precompile += %w( zeroclipboard.js )` to `config/initializers/assets.rb` and restart your server




Error log

        /root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/sprockets-rails-3.2.1/lib/sprockets/rails/helper.rb:363:in `raise_unless_precompiled_asset'
/root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/sprockets-rails-3.2.1/lib/sprockets/rails/helper.rb:337:in `digest_path'
/root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/sprockets-rails-3.2.1/lib/sprockets/rails/helper.rb:325:in `asset_path'
/root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/sprockets-rails-3.2.1/lib/sprockets/rails/helper.rb:102:in `block in resolve_asset_path'
/root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/sprockets-rails-3.2.1/lib/sprockets/rails/helper.rb:242:in `block in resolve_asset'
/root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/sprockets-rails-3.2.1/lib/sprockets/rails/helper.rb:241:in `each'
/root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/sprockets-rails-3.2.1/lib/sprockets/rails/helper.rb:241:in `detect'
/root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/sprockets-rails-3.2.1/lib/sprockets/rails/helper.rb:241:in `resolve_asset'
/root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/sprockets-rails-3.2.1/lib/sprockets/rails/helper.rb:101:in `resolve_asset_path'
/root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/sprockets-rails-3.2.1/lib/sprockets/rails/helper.rb:79:in `compute_asset_path'
/usr/local/redmine-3.4.3/config/initializers/10-patches.rb:221:in `rails_asset_id'
/usr/local/redmine-3.4.3/config/initializers/10-patches.rb:200:in `asset_path_with_asset_id'
/root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/actionview-4.2.8/lib/action_view/helpers/asset_url_helper.rb:245:in `javascript_path'
/root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/actionview-4.2.8/lib/action_view/helpers/asset_tag_helper.rb:61:in `block in javascript_include_tag'
/root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/actionview-4.2.8/lib/action_view/helpers/asset_tag_helper.rb:59:in `map'
/root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/actionview-4.2.8/lib/action_view/helpers/asset_tag_helper.rb:59:in `javascript_include_tag'
/root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/sprockets-rails-3.2.1/lib/sprockets/rails/helper.rb:156:in `block in javascript_include_tag'
/root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/sprockets-rails-3.2.1/lib/sprockets/rails/helper.rb:154:in `map'
/root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/sprockets-rails-3.2.1/lib/sprockets/rails/helper.rb:154:in `javascript_include_tag'
/usr/local/redmine-3.4.3/app/helpers/application_helper.rb:1398:in `javascript_include_tag'
/usr/local/redmine-3.4.3/plugins/vault/app/views/keys/index.html.erb:2:in `block in _plugins_vault_app_views_keys_index_html_erb___1960806769483040614_47343250682780'
/root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/actionview-4.2.8/lib/action_view/helpers/capture_helper.rb:38:in `block in capture'
/root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/actionview-4.2.8/lib/action_view/helpers/capture_helper.rb:202:in `with_output_buffer'
/root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/haml-5.0.4/lib/haml/helpers/action_view_xss_mods.rb:6:in `with_output_buffer_with_haml_xss'
/root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/actionview-4.2.8/lib/action_view/helpers/capture_helper.rb:38:in `capture'
/root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/haml-5.0.4/lib/haml/helpers/action_view_mods.rb:47:in `capture_with_haml'
/root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/actionview-4.2.8/lib/action_view/helpers/capture_helper.rb:152:in `content_for'
/usr/local/redmine-3.4.3/plugins/vault/app/views/keys/index.html.erb:1:in `_plugins_vault_app_views_keys_index_html_erb___1960806769483040614_47343250682780'
/root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/actionview-4.2.8/lib/action_view/template.rb:145:in `block in render'
/root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/activesupport-4.2.8/lib/active_support/notifications.rb:166:in `instrument'
/root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/actionview-4.2.8/lib/action_view/template.rb:333:in `instrument'
/root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/actionview-4.2.8/lib/action_view/template.rb:143:in `render'
/root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/actionview-4.2.8/lib/action_view/renderer/template_renderer.rb:54:in `block (2 levels) in render_template'
/root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/actionview-4.2.8/lib/action_view/renderer/abstract_renderer.rb:39:in `block in instrument'
/root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/activesupport-4.2.8/lib/active_support/notifications.rb:164:in `block in instrument'
/root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/activesupport-4.2.8/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/activesupport-4.2.8/lib/active_support/notifications.rb:164:in `instrument'
/root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/actionview-4.2.8/lib/action_view/renderer/abstract_renderer.rb:39:in `instrument'
/root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/actionview-4.2.8/lib/action_view/renderer/template_renderer.rb:53:in `block in render_template'
/root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/actionview-4.2.8/lib/action_view/renderer/template_renderer.rb:61:in `render_with_layout'
/root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/actionview-4.2.8/lib/action_view/renderer/template_renderer.rb:52:in `render_template'
/root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/actionview-4.2.8/lib/action_view/renderer/template_renderer.rb:14:in `render'
/root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/actionview-4.2.8/lib/action_view/renderer/renderer.rb:46:in `render_template'
/root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/actionview-4.2.8/lib/action_view/renderer/renderer.rb:27:in `render'
/root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/actionview-4.2.8/lib/action_view/rendering.rb:100:in `_render_template'
/root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/actionpack-4.2.8/lib/action_controller/metal/streaming.rb:217:in `_render_template'
/root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/actionview-4.2.8/lib/action_view/rendering.rb:83:in `render_to_body'
/root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/actionpack-4.2.8/lib/action_controller/metal/rendering.rb:32:in `render_to_body'
/root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/actionpack-4.2.8/lib/action_controller/metal/renderers.rb:37:in `render_to_body'
/root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/actionpack-4.2.8/lib/abstract_controller/rendering.rb:25:in `render'
/root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/actionpack-4.2.8/lib/action_controller/metal/rendering.rb:16:in `render'
/root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/actionpack-4.2.8/lib/action_controller/metal/instrumentation.rb:44:in `block (2 levels) in render'
/root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/activesupport-4.2.8/lib/active_support/core_ext/benchmark.rb:12:in `block in ms'
/root/.rbenv/versions/2.4.2/lib/ruby/2.4.0/benchmark.rb:308:in `realtime'
/root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/activesupport-4.2.8/lib/active_support/core_ext/benchmark.rb:12:in `ms'
/root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/actionpack-4.2.8/lib/action_controller/metal/instrumentation.rb:44:in `block in render'
/root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/actionpack-4.2.8/lib/action_controller/metal/instrumentation.rb:87:in `cleanup_view_runtime'
/root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/activerecord-4.2.8/lib/active_record/railties/controller_runtime.rb:25:in `cleanup_view_runtime'
/root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/actionpack-4.2.8/lib/action_controller/metal/instrumentation.rb:43:in `render'
/root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/actionpack-4.2.8/lib/action_controller/metal/implicit_render.rb:10:in `default_render'
/root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/actionpack-4.2.8/lib/action_controller/metal/implicit_render.rb:5:in `send_action'
/root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/actionpack-4.2.8/lib/abstract_controller/base.rb:198:in `process_action'
/root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/actionpack-4.2.8/lib/action_controller/metal/rendering.rb:10:in `process_action'
/root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/actionpack-4.2.8/lib/abstract_controller/callbacks.rb:20:in `block in process_action'
/root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:117:in `call'
/root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:555:in `block (2 levels) in compile'
/root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:505:in `call'
/root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:498:in `block (2 levels) in around'
/root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:313:in `block (2 levels) in halting'
/usr/local/redmine-3.4.3/lib/redmine/sudo_mode.rb:63:in `sudo_mode'
/root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:432:in `block in make_lambda'
/root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:312:in `block in halting'
/root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:497:in `block in around'
/root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:505:in `call'
/root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:92:in `__run_callbacks__'
/root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:778:in `_run_process_action_callbacks'
/root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:81:in `run_callbacks'
/root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/actionpack-4.2.8/lib/abstract_controller/callbacks.rb:19:in `process_action'
/root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/actionpack-4.2.8/lib/action_controller/metal/rescue.rb:29:in `process_action'
/root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/actionpack-4.2.8/lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
/root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/activesupport-4.2.8/lib/active_support/notifications.rb:164:in `block in instrument'
/root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/activesupport-4.2.8/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/activesupport-4.2.8/lib/active_support/notifications.rb:164:in `instrument'
/root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/actionpack-4.2.8/lib/action_controller/metal/instrumentation.rb:30:in `process_action'
/root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/actionpack-4.2.8/lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
/root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/activerecord-4.2.8/lib/active_record/railties/controller_runtime.rb:18:in `process_action'
/root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/actionpack-4.2.8/lib/abstract_controller/base.rb:137:in `process'
/root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/actionview-4.2.8/lib/action_view/rendering.rb:30:in `process'
/root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/actionpack-4.2.8/lib/action_controller/metal.rb:196:in `dispatch'
/root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/actionpack-4.2.8/lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
/root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/actionpack-4.2.8/lib/action_controller/metal.rb:237:in `block in action'
/root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/actionpack-4.2.8/lib/action_dispatch/routing/route_set.rb:74:in `dispatch'
/root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/actionpack-4.2.8/lib/action_dispatch/routing/route_set.rb:43:in `serve'
/root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/actionpack-4.2.8/lib/action_dispatch/journey/router.rb:43:in `block in serve'
/root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/actionpack-4.2.8/lib/action_dispatch/journey/router.rb:30:in `each'
/root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/actionpack-4.2.8/lib/action_dispatch/journey/router.rb:30:in `serve'
/root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/actionpack-4.2.8/lib/action_dispatch/routing/route_set.rb:817:in `call'
/root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/rack-openid-1.4.2/lib/rack/openid.rb:98:in `call'
/root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/request_store-1.0.5/lib/request_store/middleware.rb:9:in `call'
/root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/rack-1.6.8/lib/rack/etag.rb:24:in `call'
/root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/rack-1.6.8/lib/rack/conditionalget.rb:25:in `call'
/root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/rack-1.6.8/lib/rack/head.rb:13:in `call'
/root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/actionpack-xml_parser-1.0.2/lib/action_dispatch/xml_params_parser.rb:16:in `call'
/root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/actionpack-4.2.8/lib/action_dispatch/middleware/params_parser.rb:27:in `call'
/root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/actionpack-4.2.8/lib/action_dispatch/middleware/flash.rb:260:in `call'
/root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/rack-1.6.8/lib/rack/session/abstract/id.rb:225:in `context'
/root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/rack-1.6.8/lib/rack/session/abstract/id.rb:220:in `call'
/root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/actionpack-4.2.8/lib/action_dispatch/middleware/cookies.rb:560:in `call'
/root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/activerecord-4.2.8/lib/active_record/query_cache.rb:36:in `call'
/root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/activerecord-4.2.8/lib/active_record/connection_adapters/abstract/connection_pool.rb:653:in `call'
/root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/actionpack-4.2.8/lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
/root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:88:in `__run_callbacks__'
/root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:778:in `_run_call_callbacks'
/root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:81:in `run_callbacks'
/root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/actionpack-4.2.8/lib/action_dispatch/middleware/callbacks.rb:27:in `call'
/root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/actionpack-4.2.8/lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
/root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/actionpack-4.2.8/lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
/root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/actionpack-4.2.8/lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
/root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/railties-4.2.8/lib/rails/rack/logger.rb:38:in `call_app'
/root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/railties-4.2.8/lib/rails/rack/logger.rb:20:in `block in call'
/root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/activesupport-4.2.8/lib/active_support/tagged_logging.rb:68:in `block in tagged'
/root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/activesupport-4.2.8/lib/active_support/tagged_logging.rb:26:in `tagged'
/root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/activesupport-4.2.8/lib/active_support/tagged_logging.rb:68:in `tagged'
/root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/railties-4.2.8/lib/rails/rack/logger.rb:20:in `call'
/root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/actionpack-4.2.8/lib/action_dispatch/middleware/request_id.rb:21:in `call'
/root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/rack-1.6.8/lib/rack/methodoverride.rb:22:in `call'
/root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/rack-1.6.8/lib/rack/runtime.rb:18:in `call'
/root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/activesupport-4.2.8/lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
/root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/actionpack-4.2.8/lib/action_dispatch/middleware/static.rb:120:in `call'
/root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/rack-1.6.8/lib/rack/content_length.rb:15:in `call'
/root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/rack-1.6.8/lib/rack/sendfile.rb:113:in `call'
/root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/railties-4.2.8/lib/rails/engine.rb:518:in `call'
/root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/railties-4.2.8/lib/rails/application.rb:165:in `call'
/root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/rack-1.6.8/lib/rack/lock.rb:17:in `call'
/root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/rack-1.6.8/lib/rack/content_length.rb:15:in `call'
/root/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/rack-1.6.8/lib/rack/handler/webrick.rb:88:in `service'
/root/.rbenv/versions/2.4.2/lib/ruby/2.4.0/webrick/httpserver.rb:140:in `service'
/root/.rbenv/versions/2.4.2/lib/ruby/2.4.0/webrick/httpserver.rb:96:in `run'
/root/.rbenv/versions/2.4.2/lib/ruby/2.4.0/webrick/server.rb:290:in `block in start_thread'
      

Environment:
  Redmine version                3.4.3.stable
  Ruby version                   2.4.2-p198 (2017-09-14) [x86_64-linux]
  Rails version                  4.2.8
  Environment                    production
  Database adapter               PostgreSQL

**Comment by noshutdown-ru-user** [comment]
config/configuration.yml is in redmine (but before try use Vault encryption in plugin settings)
config/initializers/assets.rb is in redmine

**Comment by gisok** [comment]
I can enter the keys page now,but create key

**Comment by noshutdown-ru-user** [comment]
Strange you use Encryption key from config or from Vault ?

**Comment by gisok** [comment]
Thank you for your patience, thank you for tolerating my stupidity, and now it's a success

**Comment by noshutdown-ru-user** [comment]
Hey don't worry maybe you have suggestions about improve our documentation ?

**Comment by gisok** [comment]
As an administrator,I need to browse the keys of all the projects, and I need to display the notes on the browsing page

**Comment by noshutdown-ru-user** [comment]
> As an administrator,I need to browse the keys of all the projects, and I need to display the notes on the browsing page
it would be available in next major release
