### ISSUE TITLE
"Whitelist keys" не ограничивает достп к записям

### ISSUE THREAD

**Issue by Romich777** [noshutdown-ru/vault#22]
Пользователь с правами "Whitelist keys" может просматривать все ключи!
Пользователь видит общее количество ключей
![selection_001](https://user-images.githubusercontent.com/14110152/35675013-33068fd8-074f-11e8-9f23-1558c3281b26.png)

И может их просмотреть по линках
http://redmine/project/keys/1/edit
http://redmine/project/keys/2/edit

**Comment by noshutdown-ru-user** [comment]
Можно выслать скриншот настроек роли для данного пользователя ?

**Comment by Romich777** [comment]
Активна только "Whitelist keys".
Redmine 3.4.3

**Comment by noshutdown-ru-user** [comment]
Действительно, постараемся исправить как можно скорее, не используйте пока WhiteList

**Comment by Romich777** [comment]
Если не активиорвать права из группы "Keys" - пользователю не доступна вкладка "Keys".

"Whitelist keys" открывает доступ только к разрешенным пользователю ключам проэкта ?
"Viewe keys" открывает доступ ко всем ключам проэкта.

Я правильно понимаю эти права роли ?

**Comment by noshutdown-ru-user** [comment]
Спасибо что сообщили о данной уязвимости, просим протестировать https://github.com/noshutdown-ru/vault/tree/development
