### ISSUE TITLE
Can't show key list from vault tab

### ISSUE THREAD

**Issue by camlafit** [noshutdown-ru/vault#24]
Hello 

I've just installed plugin on my instance : 
```
Environment:
  Redmine version                3.3.1.stable
  Ruby version                   2.3.3-p222 (2016-11-21) [i386-linux-gnu]
  Rails version                  4.2.10
  Environment                    production
  Database adapter               SQLite
SCM:
  Subversion                     1.9.5
  Git                            2.11.0
  Filesystem                     
  GitRemote                      2.11.0
Redmine plugins:
  redmine_default_custom_query   1.1.2
  redmine_git_remote             0.0.1
  redmine_spent_time             3.1.2
  redmine_tweaks                 1.0.0
  redmine_wktime                 2.7
  vault                          0.3.6
```

In role management I've enabled all options related to this plugin.
I can add without problem a key, from vault admin page I can export data and see all key added.

But from vault project tab, I get a 500 error  ( projects/projects1/keys?utf8=✓&query=mat&commit=Mettre+à+jour ) 

```
Started GET "/projects/projects1/keys?utf8=%E2%9C%93&query=mat&commit=Mettre+%C3%A0+jour" for 88.190.92.83 at 2018-02-19 17:14:56 +0100
Processing by KeysController#index as HTML
  Parameters: {"utf8"=>"�", "query"=>"mat", "commit"=>"Mettre à jour", "project_id"=>"projects1"}
  Current user: admin (id=3)
Completed 500 Internal Server Error in 143ms (ActiveRecord: 97.9ms)

NoMethodError (private method `select' called for nil:NilClass):
  plugins/vault/app/controllers/keys_controller.rb:51:in `index'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'
```

**Comment by noshutdown-ru-user** [comment]
Search is broken, /projects/projects1/keys without should work, we will fix it

**Comment by camlafit** [comment]
Hello

No more error with a search :) But key listing stay empty with(out) search.

**Comment by noshutdown-ru-user** [comment]
press `clear` button )

**Comment by noshutdown-ru-user** [comment]
also disable in role configuration `Whitelisted keys`

**Comment by noshutdown-ru-user** [comment]
https://user-images.githubusercontent.com/22587828/35121157-89d1ae32-fcab-11e7-83a6-9ed5c0b84295.png 
if you use whitelisted keys for this role you need add this user in whitelist for each key in project

**Comment by camlafit** [comment]
Hello

Ok was _Whitelisted keys_ option , I've misunderstood this feature. Thank a lot :)

**Comment by noshutdown-ru-user** [comment]
You welcome, we working around of new ,more clear for understanding, logic
