### ISSUE TITLE
Copy to clipboard

### ISSUE THREAD

**Issue by antopgs** [noshutdown-ru/vault#28]
With redmine 3.4    the function (link) to copy key to clipboard not working.

![image](https://user-images.githubusercontent.com/37363516/37390274-b24fc6b4-2767-11e8-844c-81a4beb65b86.png)

**Comment by noshutdown-ru-user** [comment]
have you tried use right click for copy ?

**Comment by antopgs** [comment]
Yes right click works fine

**Comment by verfriemelt-dot-org** [comment]
+1 same issue

**Comment by noshutdown-ru-user** [comment]
We will try solve it during couple of weeks, sorry

**Comment by verfriemelt-dot-org** [comment]
i hope you could use my patches to release a new version which fixes this issue :)

**Comment by noshutdown-ru-user** [comment]
sure, we will check it today , thx for contribution
