### ISSUE TITLE
Actions column should be Comment column ?

### ISSUE THREAD

**Issue by antopgs** [noshutdown-ru/vault#29]
I don't know what the "Actions" column supposed to show ?

It's always empty, even if all fields are filled

**Comment by noshutdown-ru-user** [comment]
![vault-menu](https://user-images.githubusercontent.com/22587828/37390960-d1d838d2-277a-11e8-833d-206a40cf947c.jpeg)

it should contains buttons edit/delete/view

**Comment by noshutdown-ru-user** [comment]
you use Admin account for view ?

**Comment by antopgs** [comment]
Oh yes of course ...., shame on me.. 
Thank you

**Comment by noshutdown-ru-user** [comment]
you welcome)
