### ISSUE TITLE
Table size in PDF

### ISSUE THREAD

**Issue by peterbeck** [noshutdown-ru/vault#3]
Is it possible to resize the tables in the pdf output ?
For example, i don't need such a long URL field, but would prefer a bigger "login" table.
How can I achieve that ?

**Comment by noshutdown-ru-user** [comment]
you can try change some values here ./app/helpers/keys_helper.rb
` # Landscape A4 = 210 x 297 mm
    page_height   = pdf.get_page_height # 210
    page_width    = pdf.get_page_width  # 297
    left_margin   = pdf.get_original_margins['left'] # 10
    right_margin  = pdf.get_original_margins['right'] # 10
    bottom_margin = pdf.get_footer_margin
    row_height    = 4

    # column widths
    table_width = page_width - right_margin - left_margin`

**Comment by noshutdown-ru-user** [comment]
we think about custom templates for pdf

**Comment by peterbeck** [comment]
perfect - I could manage to adjust the tables via RDMMultiCell

Thanks a lot for this great plugin !
