### ISSUE TITLE
Error 500 on key create

### ISSUE THREAD

**Issue by DProvorse** [noshutdown-ru/vault#30]
WARNING: Can't mass-assign protected attributes for Vault::Password: tags
        plugins/vault/app/controllers/keys_controller.rb:80:in `create'
        lib/redmine/sudo_mode.rb:63:in `sudo_mode'
Completed 500 Internal Server Error in 36ms (ActiveRecord: 7.4ms)

ArgumentError (must specify a :key):
  plugins/vault/app/models/vault/password.rb:8:in `encrypt!'
  plugins/vault/app/controllers/keys_controller.rb:88:in `block in create'
  plugins/vault/app/controllers/keys_controller.rb:87:in `create'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'

Getting the above error anytime I try to create a new key.

Redmine 3.4.4
Ruby 2.2.6-p396
Rails 4.2.8
plugin 0.3.7

I'm also getting a seperate error if I try to run rake redmine:plugins:vault:convert

redmine@projects:~/redmine/config$ rake redmine:plugins:vault:convert RAILS_ENV=production --trace
(in /home/redmine/redmine)
** Invoke redmine:plugins:vault:convert (first_time)
** Invoke environment (first_time)
** Execute environment
** Execute redmine:plugins:vault:convert
rake aborted!
NoMethodError: undefined method `decrypt_all' for Encryptor:Module
/home/redmine/redmine/plugins/vault/lib/tasks/ciphering.rake:25:in `block (4 levels) in <top (required)>'
/home/redmine/.rvm/gems/ruby-2.2.6/gems/rake-12.3.0/lib/rake/task.rb:251:in `call'
/home/redmine/.rvm/gems/ruby-2.2.6/gems/rake-12.3.0/lib/rake/task.rb:251:in `block in execute'
/home/redmine/.rvm/gems/ruby-2.2.6/gems/rake-12.3.0/lib/rake/task.rb:251:in `each'
/home/redmine/.rvm/gems/ruby-2.2.6/gems/rake-12.3.0/lib/rake/task.rb:251:in `execute'
/home/redmine/.rvm/gems/ruby-2.2.6/gems/rake-12.3.0/lib/rake/task.rb:195:in `block in invoke_with_call_chain'
/home/redmine/.rvm/rubies/ruby-2.2.6/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
/home/redmine/.rvm/gems/ruby-2.2.6/gems/rake-12.3.0/lib/rake/task.rb:188:in `invoke_with_call_chain'
/home/redmine/.rvm/gems/ruby-2.2.6/gems/rake-12.3.0/lib/rake/task.rb:181:in `invoke'
/home/redmine/.rvm/gems/ruby-2.2.6/gems/rake-12.3.0/lib/rake/application.rb:160:in `invoke_task'
/home/redmine/.rvm/gems/ruby-2.2.6/gems/rake-12.3.0/lib/rake/application.rb:116:in `block (2 levels) in top_level'
/home/redmine/.rvm/gems/ruby-2.2.6/gems/rake-12.3.0/lib/rake/application.rb:116:in `each'
/home/redmine/.rvm/gems/ruby-2.2.6/gems/rake-12.3.0/lib/rake/application.rb:116:in `block in top_level'
/home/redmine/.rvm/gems/ruby-2.2.6/gems/rake-12.3.0/lib/rake/application.rb:125:in `run_with_threads'
/home/redmine/.rvm/gems/ruby-2.2.6/gems/rake-12.3.0/lib/rake/application.rb:110:in `top_level'
/home/redmine/.rvm/gems/ruby-2.2.6/gems/rake-12.3.0/lib/rake/application.rb:83:in `block in run'
/home/redmine/.rvm/gems/ruby-2.2.6/gems/rake-12.3.0/lib/rake/application.rb:186:in `standard_exception_handling'
/home/redmine/.rvm/gems/ruby-2.2.6/gems/rake-12.3.0/lib/rake/application.rb:80:in `run'
/home/redmine/.rvm/gems/ruby-2.2.6/gems/rake-12.3.0/exe/rake:27:in `<top (required)>'
/home/redmine/.rvm/gems/ruby-2.2.6/bin/rake:22:in `load'
/home/redmine/.rvm/gems/ruby-2.2.6/bin/rake:22:in `<main>'
/home/redmine/.rvm/gems/ruby-2.2.6/bin/ruby_executable_hooks:15:in `eval'
/home/redmine/.rvm/gems/ruby-2.2.6/bin/ruby_executable_hooks:15:in `<main>'

**Comment by noshutdown-ru-user** [comment]
It looks what you did something wrong similar as here https://github.com/noshutdown-ru/vault/issues/27.
1) It is new installation ? if yes and you don't have any keys you and you won't use Redmine encription, not Vault,  you just need define Encryption key in config file and restart redmine, after this you will allow to create keys.

**Comment by noshutdown-ru-user** [comment]
if you don't have any keys you should't run ` rake redmine:plugins:vault:convert`
it needed only if you migrate old keys from Vault encryption to Redmine encryption

**Comment by DProvorse** [comment]
Not a new install, define_cypher_key is already in config. Key matches between config and Vault settings as well.

**Comment by noshutdown-ru-user** [comment]
hmm, we will check

**Comment by DProvorse** [comment]
database_cipher_key: '*************************'

redacted the key but that is how it looks inside of the configuration.yml

**Comment by noshutdown-ru-user** [comment]
we checked in our ENV.
1) We set encryption key (16 bytes): `jailNapcitnuWyd3` 
2) Create test key.
3) Stop Redmine
4) Add in config/configuration.yml string `database_cipher_key: coivgikburjIlIsAfalyurjyesukvihi`
5) Start Redmine
6) Enable checkbox `Use Redmine encryption`
7) Checked what test key now is unreadable
8) Stop Redmine
9) Run rake redmine:plugins:vault:convert RAILS_ENV=production
10) Start Redmine
11) Checked what test key now is readable 

Before make database backup, also you can play with it use this repo: https://github.com/noshutdown-ru/vagrant_redmine

**Comment by noshutdown-ru-user** [comment]
Strange, what encryption you use ?

**Comment by noshutdown-ru-user** [comment]
We will check on same Ruby version as you have

**Comment by noshutdown-ru-user** [comment]
database_cipher_key: 1234567812345678
Vault encryption key : 1234567812345678
no error, have you tried it https://github.com/noshutdown-ru/vagrant_redmine

**Comment by noshutdown-ru-user** [comment]
Also can you try create key from Admin user

**Comment by DProvorse** [comment]
Got it figured out, there was a conflict with an existing plugin that I had installed called 'Redmine Passwords'. We no longer use that so I dropped it out and purged it, after doing that everything is encrypting and working perfectly!
