### ISSUE TITLE
Allow access by group

### ISSUE THREAD

**Issue by daltinn** [noshutdown-ru/vault#35]
In dynamic development group very useful grant access to key by group

**Comment by verfriemelt-dot-org** [comment]
+1

**Comment by georgerizescu** [comment]
+1

**Comment by paimpozhil** [comment]
+1

**Comment by noshutdown-ru-user** [comment]
Thx for voting, will try push this feature forward

**Comment by noshutdown-ru-user** [comment]
pls take a look in dev pranch https://github.com/noshutdown-ru/vault/tree/development
