### ISSUE TITLE
ActionView::Template::Error (incompatible character encodings: UTF-8 and ASCII-8BIT):

### ISSUE THREAD

**Issue by if22** [noshutdown-ru/vault#37]
Hey!
We faced of with problem:
```Started GET "/projects/crm/keys" for IP and date +0700
Processing by KeysController#index as HTML
  Parameters: {"project_id"=>"crm"}
  Current user: user (id=3)
  Rendered plugins/vault/app/views/shared/_key_fields.html.erb (0.3ms)
  Rendered plugins/vault/app/views/vault/passwords/_password.html.erb (1.5ms)
  Rendered plugins/vault/app/views/keys/index.html.erb within layouts/base (4.7ms)
Completed 500 Internal Server Error in 19ms (ActiveRecord: 4.3ms)

ActionView::Template::Error (incompatible character encodings: UTF-8 and ASCII-8BIT):
     7:     <% unless password.body.blank? %>
     8: 
     9:       <label>*********</label>
    10:       <label id='plain_pass_<%=password.id%>' style='display:none;'><%= password.body %></label>
    11: 
    12:       <a align="left" class='keys-actions copy-key' data-clipboard-target='plain_pass_<%=password.id%>' title='<%=t('key.btn.clipboard')%>'>
    13:         <i class="fa fa-clipboard fa-fw"></i>
  plugins/vault/app/views/vault/passwords/_password.html.erb:10:in `_plugins_vault_app_views_vault_passwords__password_html_erb__1521033087661395652_69908829726360'
  plugins/vault/app/views/keys/index.html.erb:49:in `block (2 levels) in _plugins_vault_app_views_keys_index_html_erb__3488128115211990408_69908830743220'
  plugins/vault/app/views/keys/index.html.erb:48:in `each'
  plugins/vault/app/views/keys/index.html.erb:48:in `block in _plugins_vault_app_views_keys_index_html_erb__3488128115211990408_69908830743220'
  plugins/vault/app/views/keys/index.html.erb:34:in `_plugins_vault_app_views_keys_index_html_erb__3488128115211990408_69908830743220'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'

Processing by UsErrorsController#error_500 as HTML```

How can I fix this error?


P.S.
```Environment:
  Redmine version                3.4.5.stable
  Ruby version                   2.3.4-p301 (2017-03-30) [x86_64-linux]
  Rails version                  4.2.8
  Environment                    production
  Database adapter               Mysql2```

**Comment by noshutdown-ru-user** [comment]
You can easily rollback to old 0.3.7, it not affect database migration, we take a look asap

**Comment by noshutdown-ru-user** [comment]
fixed, you can try development branch

**Comment by if22** [comment]
Great! Fixed! Thanks!

**Comment by if22** [comment]
The same thing is on Key edit page `keys/8/edit`.

**Comment by noshutdown-ru-user** [comment]
we will check

**Comment by if22** [comment]
Processing by KeysController#edit as HTML
  Parameters: {"project_id"=>"crm", "id"=>"8"}
  Current user: 
  Rendered plugins/vault/app/views/keys/_form.html.erb (1.5ms)
  Rendered plugins/vault/app/views/keys/edit.html.erb within layouts/base (1.8ms)
Completed 500 Internal Server Error in 9ms (ActiveRecord: 2.3ms)

ActionView::Template::Error (incompatible character encodings: UTF-8 and ASCII-8BIT):
    26: 
    27:     <p><%= f.label :body, t('key.attr.body') %>
    28:     <% if User.current.allowed_to?(:edit_keys, @project) %>
    29:       <%= f.text_field :body %></p>
    30:     <% else %>
    31:       <%= f.text_field :body,:readonly => true %></p>
    32:     <% end %>
  plugins/vault/app/views/keys/_form.html.erb:29:in `block in _plugins_vault_app_views_keys__form_html_erb___93919382263552648_69902359935940'
  plugins/vault/app/views/keys/_form.html.erb:1:in `_plugins_vault_app_views_keys__form_html_erb___93919382263552648_69902359935940'
  plugins/vault/app/views/keys/edit.html.erb:3:in `_plugins_vault_app_views_keys_edit_html_erb__1869552060845857255_69902359461800'
  plugins/vault/app/controllers/keys_controller.rb:128:in `block (2 levels) in edit'
  plugins/vault/app/controllers/keys_controller.rb:127:in `edit'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'

**Comment by noshutdown-ru-user** [comment]
try now

**Comment by noshutdown-ru-user** [comment]
pull from master
