### ISSUE TITLE
HTTP ERROR 500 when add file in add key

### ISSUE THREAD

**Issue by MABgi** [noshutdown-ru/vault#39]
Когда добавляешь файл в поле "файл ключа" и нажимаешь "сохранить" попадаешь на страницу HTTP ERROR 500
![image](https://user-images.githubusercontent.com/30617189/41899928-3a5d50ce-7936-11e8-881f-d8888446f6aa.png)
Сама ошибка:
![image](https://user-images.githubusercontent.com/30617189/41899958-47ce069a-7936-11e8-829b-351826ea6539.png)
Не знаете в чем может быть проблема?

**Comment by noshutdown-ru-user** [comment]
При закгрузке файла нужно выбрать тип ключа Фаил

**Comment by MABgi** [comment]
Попробовал - та же ошибка...

**Comment by noshutdown-ru-user** [comment]
можете показать лог фаил ?

**Comment by MABgi** [comment]
Прошу прощения за мою глупость, расширил логи: не хватало прав на запись в папку redmine/keys
