### ISSUE TITLE
Зря удалили иконки копирования

### ISSUE THREAD

**Issue by radist** [noshutdown-ru/vault#4]
Раньше была иконка копирования рядом с колонкой Url теперь урл можно скопировать через меню, что на пару кликов длинней.
Я использую поле урл не только для хранения урлов но и для хранения вот такой строки:

`ssh user@host.ru -p 2244`

удобно копировать было, а не набирать.

**Comment by noshutdown-ru-user** [comment]
Спасибо что написали данное замечание.
Мы хотели избавится от большого количество кнопок.
Подумаем как это сделать удобней.

**Comment by noshutdown-ru-user** [comment]
Исправили в версии 0.3.2 https://noshutdown.ru/redmine-plugins-vault/
Теперь можно копировать в буфер поля login, url при клике на само поле.
