### ISSUE TITLE
Keys can't be longer than 32 characters

### ISSUE THREAD

**Issue by dktcoding** [noshutdown-ru/vault#43]
When a password has at most 31 chars there's no problem:

![screen shot 2018-11-25 at 02 05 11](https://user-images.githubusercontent.com/709639/48975734-9f950f80-f056-11e8-80fa-44124ef2b145.png)

But when a password is more than 31 chars long:

![screen shot 2018-11-25 at 02 05 20](https://user-images.githubusercontent.com/709639/48975735-ae7bc200-f056-11e8-8db7-f90651667206.png)

Is this by design?

---
Redmine 3.4.6 
Using Redmine encryption with a 128 char password

**Comment by noshutdown-ru-user** [comment]
Hi, thx for your report, we take a look about limits of password

**Comment by noshutdown-ru-user** [comment]
We not forget about issue =) hopefully will fix it in couple of days

**Comment by noshutdown-ru-user** [comment]
Can you try development branch, to check fix

**Comment by dktcoding** [comment]
Hi there!

Yes, issue appears to be fixed in the development branch!

![screen shot 2018-12-09 at 14 38 33](https://user-images.githubusercontent.com/709639/49700631-205c1b80-fbc0-11e8-9e1a-bc5234640264.png)

**Comment by noshutdown-ru-user** [comment]
during a week we will release new version, with  this fixes
