### ISSUE TITLE
Restore from backup to batch import new/modified keys

### ISSUE THREAD

**Issue by jmtemmos** [noshutdown-ru/vault#44]
Hi. I tried to import a slighly modified backup to add new keys or to change project_ids.

What I did

* I tried to backup => backup.zip
* then I unzipped and modified manually keys.csv, trying something as simple as changing the project id.
* I zipped again the files as backup_new.zip
* I used the plugin interface to restore from backup
* restore complete, but no project id changed, no new keys created

Import works fine but the no new key is created and project id cannot be changed either.
Nothing special from the logs
Redmine 3.4.6 stable

Your plugin is really great, need to find a solution :)

Thanks for your help

**Comment by noshutdown-ru-user** [comment]
we take a look, during weekends )

**Comment by jmtemmos** [comment]
You are fantastic. Sorry for that stupid mistake: yes, I zipped the containing folder. It works fine now. Thanks a lot. Very useful !

**Comment by noshutdown-ru-user** [comment]
when we reproduced your case we did same mistake ;)
