### ISSUE TITLE
Menu admin no show Icon

### ISSUE THREAD

**Issue by vsc55** [noshutdown-ru/vault#46]
In the admin menu no show icon.
Is run Redmine 4.0.1.stable.17836 and vault 0.3.11.

![noticon](https://user-images.githubusercontent.com/13438676/51472535-0d6d6700-1d7a-11e9-958d-21a499115c12.png)

**Comment by noshutdown-ru-user** [comment]
This is strange we checked on new installation and icon exist.
<img width="1213" alt="screenshot 2019-01-27 at 21 09 06" src="https://user-images.githubusercontent.com/22587828/51804934-f053ff00-2277-11e9-8c0a-d26adb1bb26c.png">

**Comment by noshutdown-ru-user** [comment]
vault.css in folder plugin_assets ? maybe it not copied ?
can you also add browser log/errors

**Comment by vsc55** [comment]
Hi,
If the vault.css file is copied correctly.
I have been doing tests and in the end I have detected that the problem occurs when the Logs plugin (https://github.com/haru/redmine_logs) is installed.
It seems an incompatibility between the two plugins.

**Comment by noshutdown-ru-user** [comment]
we will try install this plugin and will try find where is conflict between the two plugins

**Comment by vsc55** [comment]
OK thank you very much.

**Comment by noshutdown-ru-user** [comment]
You can update branch pull https://github.com/noshutdown-ru/vault/tree/redmine_4.0.
Should be fixed now.
