### ISSUE TITLE
Error in redmine subdir

### ISSUE THREAD

**Issue by JDStar** [noshutdown-ru/vault#47]
My redmine is in URI  example https://my.domain.rm/redmine/.
Your plugin use non relative path to URI like:
`#admin-menu a.vault { background-image: url("/images/locked.png"); }`
and if I try save parameters in vault plugin server return 404 code because save action make:
`https://my.domain.rm/vault_settings` instead of corrected in my redmine instance `https://my.domain.rm/redmine/vault_settings`

**Comment by noshutdown-ru-user** [comment]
we take a look

**Comment by noshutdown-ru-user** [comment]
should be fine now in https://github.com/noshutdown-ru/vault/tree/development
