### ISSUE TITLE
API interface

### ISSUE THREAD

**Issue by majkinetor** [noshutdown-ru/vault#54]
Is it possible to get keys via API or something ?

**Comment by noshutdown-ru-user** [comment]
yes we can implement it

**Comment by AizeLeOuf** [comment]
Need it !

**Comment by noshutdown-ru-user** [comment]
ok ok ) we will try to do it soon

**Comment by noshutdown-ru-user** [comment]
pls take a look in https://github.com/noshutdown-ru/vault/tree/development
http --json GET http://redmine.server/projects/test1/keys.json key=<api token>
