### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by Gesss** [noshutdown-ru/vault#62]
Hi,
I'm having a problem with installation. I get rake error.

Environment:
  Redmine version                4.0.5.stable
  Ruby version                   2.5.5-p157 (2019-03-15) [x86_64-linux]
  Rails version                  5.2.3

Vault version: 0.4.1

rake aborted!
StandardError: An error has occurred, all later migrations canceled:

Directly inheriting from ActiveRecord::Migration is not supported. Please specify the Rails release the migration was written for:
  class CreateEnumPrices < ActiveRecord::Migration[4.2]

Any ideas?

**Comment by noshutdown-ru-user** [comment]
Will investigate it.

**Comment by Gesss** [comment]
@noshutdown-ru-user any news?

**Comment by noshutdown-ru-user** [comment]
We checked and new installation works fine, we tried it in Vagrant https://github.com/noshutdown-ru/vagrant_redmine

Environment:
  Redmine version                4.0.5.stable
  Ruby version                   2.7.0-p0 (2019-12-25) [x86_64-linux]
  Rails version                  5.2.3
  Environment                    production
  Database adapter               SQLite
  Mailer queue                   ActiveJob::QueueAdapters::AsyncAdapter
  Mailer delivery                smtp
SCM:
  Git                            1.8.3.1
  Filesystem                     
Redmine plugins:
  vault                          0.4.1

**Comment by noshutdown-ru-user** [comment]
```
# cd /opt/redmine/plugins/vault/
# grep -R CreateEnumPrices ./
```

we don't have any migrations like this

**Comment by Gesss** [comment]
Ok. Thank you for helping.

**Comment by noshutdown-ru-user** [comment]
> Ok. Thank you for helping.

But did you found source of issue ?
