### ISSUE TITLE
Update russiant translation

### ISSUE THREAD

**Issue by Luckyvb** [noshutdown-ru/vault#63]
diff --git a/config/locales/ru.yml b/config/locales/ru.yml
index bd41238..45ec3ab 100644
--- a/config/locales/ru.yml
+++ b/config/locales/ru.yml
@@ -2,6 +2,13 @@
 ru:
   label_vault: 'Vault'
   label_module: 'Ключи'
\+  project_module_keys: "Ключи"
\+  permission_export_keys: "Экспортировать ключи"
\+  permission_download_keys: "Скачивать ключи"
\+  permission_view_keys: "Просматривать ключи"
\+  permission_edit_keys: "Редактировать ключи"
\+  permission_manage_whitelist_keys: "Управлять списками доступа"
\+  permission_whitelist_keys: "Списки доступа"
   settings:
     title: "Настройки Vault"
     vault_title_encription_key: "Ключ шифрования"

**Comment by noshutdown-ru-user** [comment]
Thx for PR, we will take a look

**Comment by mr-exz** [comment]
released in 0.5.0
