### ISSUE TITLE
Cannot bundle

### ISSUE THREAD

**Issue by sphereweb83** [noshutdown-ru/vault#65]
When i try to bundle following the installation guide, i get the following error:

> 

> bit@XXX:~/apps/redmine/htdocs/plugins$ bundle install --without development test
> 
> [!] There was an error parsing `Gemfile`:
> [!] There was an error parsing `Gemfile`: You cannot specify the same gem twice with different version requirements.
> You specified: protected_attributes_continued (>= 0) and protected_attributes_continued (= 1.4.0). Bundler cannot continue.
> 
>   from /opt/bitnami/apps/redmine/htdocs/plugins/vault/Gemfile:14
>    -------------------------------------------
>    if Gem::Version.new(redmine_version_major) >= Gem::Version.new('4')
>  >    gem 'protected_attributes_continued', '1.4.0'
>    end
>    -------------------------------------------
> . Bundler cannot continue.
> 
>    from /opt/bitnami/apps/redmine/htdocs/Gemfile:99
>    -------------------------------------------
>    Dir.glob File.expand_path("../plugins/*/{Gemfile,PluginGemfile}", __FILE__) do |file|
>  >    eval_gemfile file
>    end
>    -------------------------------------------
>

**Comment by noshutdown-ru-user** [comment]
Can you try comment line 14 in our Gemfile and try again ?

**Comment by sphereweb83** [comment]
Worked, thanks
