### ISSUE TITLE
Не сохраняется ключ если записать пароль

### ISSUE THREAD

**Issue by iamalexgrey** [noshutdown-ru/vault#66]
Добрый день!
Редмайн 4.1.1, после установки плагина vault (с закоментированной 14ой строкой, таже проблема что в обращении #65 ) я ввел ключ шифрования
![Screenshot from 2020-06-02 00-04-59](https://user-images.githubusercontent.com/33861735/83435225-07a38d80-a466-11ea-80f8-cdc07ad54dd5.png)
После чего заполняю ключ в хранилище
![Screenshot from 2020-06-02 00-03-33](https://user-images.githubusercontent.com/33861735/83435291-243fc580-a466-11ea-9a0b-f2697b30eb2f.png)
и сервер выдает такую ошибку
![Screenshot from 2020-06-02 00-04-03](https://user-images.githubusercontent.com/33861735/83435327-36b9ff00-a466-11ea-8a63-e3b4a97aab7d.png)
В логах при этом появляется:

  Current user: admin (id=1)
WARNING: Can't mass-assign protected attributes for Vault::Password: tags
	plugins/vault/app/controllers/keys_controller.rb:112:in `block in update'
	plugins/vault/app/controllers/keys_controller.rb:108:in `update'
	lib/redmine/sudo_mode.rb:65:in `sudo_mode'
Completed 500 Internal Server Error in 17ms (ActiveRecord: 8.0ms)
  
ArgumentError (key must be 16 bytes):
  
plugins/vault/lib/vault_cipher.rb:9:in `key='
plugins/vault/lib/vault_cipher.rb:9:in `encrypt_text'
plugins/vault/lib/encryptor.rb:6:in `encrypt'
plugins/vault/app/models/vault/password.rb:8:in `encrypt!'
plugins/vault/app/controllers/keys_controller.rb:112:in `block in update'
plugins/vault/app/controllers/keys_controller.rb:108:in `update'
lib/redmine/sudo_mode.rb:65:in `sudo_mode'

**Comment by noshutdown-ru-user** [comment]
попробуйте ключ шифрования длинной именно 16 символов

**Comment by iamalexgrey** [comment]
Отлично все работает, спасибо большое!
