### ISSUE TITLE
Using vault with redmine in /redmine

### ISSUE THREAD

**Issue by varenius** [noshutdown-ru/vault#67]
Hello,
I want to try vault on my redmine 4 installation. I am running redmine in a subdir of my side, i.e. https://www.example.com/redmine. I go to https://www.example.com/redmine/vault_settings and check the "Use Redmine encryption" box, and then click "Apply". When I do, I get a "404 not found" as my browser tries to go to https://www.example.com/vault_settings instead of https://www.example.com/redmine/vault_settings. Is this a problem with vault? Or, have I configured my redmine site in some erroneous way when using the subdir?

Grateful for any ideas.

**Comment by noshutdown-ru-user** [comment]
sorry for long delay, we will check it during this/next week
