### ISSUE TITLE
Permissions not set after install and  Project manager/owner is not default in the "Selected Members"

### ISSUE THREAD

**Issue by EduardoCastanho** [noshutdown-ru/vault#68]
Hi !
After installing the plugin , 
it only was available for the admin, because the permissions aren't set for any other roles
After changing the permissions
On creating a new entry the user(Role Manager)  is not included in the Selected Members by default  witch makes the new entry unavailable for the user  and only the admin can revert this .

Something went wrong in the installation right?

```
Environment:
  Redmine version                4.1.1.stable
  Ruby version                   2.6.5-p114 (2019-10-01) [x86_64-linux]
  Rails version                  5.2.4.2
  Environment                    production
  Database adapter               PostgreSQL
  Mailer queue                   ActiveJob::QueueAdapters::AsyncAdapter
  Mailer delivery                smtp
SCM:
  Git                            2.29.2
  Filesystem                     
Redmine plugins:
  additionals                    3.0.0
  ipma_custom                    0.0.1
  redmine_all_thumbnails         1.0.5
  redmine_announcements          2.0.0
  redmine_callout_macro          1.0.0
  redmine_issue_dynamic_edit     0.7.2
  redmine_issues_tree            0.0.14
  redmine_lightbox2              0.5.1
  redmine_more_code              1.0.1
  redmine_preview_inline         1.0.3
  redmine_wysiwyg_editor         0.18.0
  vault                          0.4.1

```

**Comment by noshutdown-ru-user** [comment]
Hey let us check

**Comment by noshutdown-ru-user** [comment]
Not really understandable logic, we will try improve it.
Roles and permissions:Keys have 2 modes:
1) if Whitelist keys enabled - for users with role where it is active will work Whitelist per key 
2) if Whitelist keys disabled - for users with role where it is inactive will work other restrictions edit/view all keys

so in your keys try uncheck `Whitelist keys`
