### ISSUE TITLE
Other Problems with Redmine 4.2.1

### ISSUE THREAD

**Issue by CSCSxx** [noshutdown-ru/vault#75]
Installation was no problem
Try to access:
Started GET "/projects/.../keys" for 127.0.0.1 at 2021-05-09 16:33:01 +0000
Processing by KeysController#index as HTML
  Parameters: {"project_id"=>"..."}
  Current user: ... (id=1)
  Rendering plugins/vault/app/views/keys/index.html.erb within layouts/base
  Rendered plugins/vault/app/views/keys/index.html.erb within layouts/base (182.7ms)
Completed 500 Internal Server Error in 282ms (ActiveRecord: 38.7ms)
  
ActionView::Template::Error (wrong number of arguments (given 1, expected 0)):
    78: <% if Redmine::VERSION.to_s.start_with?('3.4', '4.0', '4.1')  %>
    79:     <%= context_menu %>
    80: <% else %>
    81:     <%= context_menu project_keys_context_menus_path(@project) %>
    82: <% end %>
    83: 
    84: <script type="text/javascript">

**Comment by noshutdown-ru-user** [comment]
Sec, will take a look

**Comment by noshutdown-ru-user** [comment]
Should be fixed in 0.4.2 version, pull latest master branch version, and retry.
