### ISSUE TITLE
Redmine 5.0

### ISSUE THREAD

**Issue by lluisgener** [noshutdown-ru/vault#91]
Hello.

Is it possible to make the plugin compatible with new redmine 5?

There seems to be a compatibility issue with the new Zeitwerk loader.

Thanks in advance.

**Comment by JanB97** [comment]
I managed to get it to work for me, but there are still issues.
Search isn't working and reload isn't either.
I can send you my files if you want, as I can not remember what all I changed anymore.

**Comment by lluisgener** [comment]
If you can, I would appreciate it.

Thanks.

**Comment by noshutdown-ru-user** [comment]
Our debt is growing but we will try

**Comment by noshutdown-ru-user** [comment]
pls append your changed or you can open PR with changes

**Comment by lluisgener** [comment]
I made the atteched vault.zip work by adding this to the gemfile:

`if Gem::Version.new(redmine_version_major) >= Gem::Version.new('4')
  gem 'protected_attributes_continued', '1.8.2'
end`

and replacing line 112 in keys_controller.rb for:

`      if @key.update(params[:vault_key])`

It seems to read the previous keys, and I've been able to add, update and delete new ones.

**Comment by rohitthakral** [comment]
Ok so I have tried the change by @JanB97 and the updates by @lluisgener as well but I keep getting this:

```
Zeitwerk::NameError: expected file /opt/redmine/plugins/vault/lib/mk_keyfiles_dir.rb to define constant MkKeyfilesDir, but didn't
/var/lib/gems/2.7.0/gems/zeitwerk-2.6.4/lib/zeitwerk/loader/callbacks.rb:25:in `on_file_autoloaded'
/var/lib/gems/2.7.0/gems/zeitwerk-2.6.4/lib/zeitwerk/kernel.rb:42:in `require'

```

**Comment by rohitthakral** [comment]
Ignore, I was trying to use the repository and not the zip provided  by @JanB97 .

Thank you guys for your help. I will try and see if I can commit this through my repository and get back to you with a merge request.

**Comment by mr-exz** [comment]
0.5.0 released
